name: deb
on:
  - push
  - pull_request
  - schedule:
    cron: '0 0 * * 0'
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-node@v1
        with:
          node-version: 11.12
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install
        run: npm i
      - name: go
        run: make go
      - name: deb
        run: make deb
