name: build
on:
  - push
  - pull_request
  - schedule:
    cron: '0 0 * * 0'
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go test -count=1 -cover '-race' ./...
